apiVersion: v1
kind: Template
metadata:
  name: edb-cluster-template
objects:
- apiVersion: postgresql.k8s.enterprisedb.io/v1
  kind: Cluster
  metadata:
    name: ${CLUSTER_NAME}
  spec:
    imageName: quay.io/enterprisedb/postgresql:${POSTGRES_VERSION}
    instances: ${{CLUSTER_REPLICAS}}
    licenseKey: ${CLUSTER_LICENSE}
    primaryUpdateStrategy: unsupervised
    storage:
      storageClass: ${STORAGE_CLASS}
      size: ${STORAGE_SIZE}
    resources:
      requests:
        memory: "${REQUEST_MEMORY}"
        cpu: "${REQUEST_CPU}"
      limits:
        memory: "${LIMIT_MEMORY}"
        cpu: "${LIMIT_CPU}"
parameters:
- name: CLUSTER_NAME
  description: The name of the cluster object, also used to mark the secrets as belonging to a specific cluster
  required: true
- name: CLUSTER_LICENSE
  value: ""
- name: POSTGRES_VERSION
  value: "13.2"
  required: true
- name: CLUSTER_REPLICAS
  value: "3"
  required: true
- name: STORAGE_CLASS
  value: "netapp-block-standard"
  required: true
- name: STORAGE_SIZE
  value: "1Gi"
  required: true
- name: REQUEST_MEMORY
  value: "256Mi"
  required: true
- name: REQUEST_CPU
  value: "500m"
  required: true
- name: LIMIT_MEMORY
  value: "1Gi"
  required: true
- name: LIMIT_CPU
  value: "2"
  required: true

