apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-sample
  namespace: caggles-test
spec:
  storage:
    size: 1Gi
  primaryUpdateStrategy: unsupervised
  instances: 3
